codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 75%
        threshold: 5%
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

github_checks:
  annotations: true

ignore:
  - "coverage/"
  - "coverage-*/"
  - "**/*.test.ts"
  - "**/*.test.tsx" 
  - "__tests__/"
  - "scripts/"
  - "docs/"
  - "ios/"
  - "android/"
  - "node_modules/"
  - ".expo/"